export type CategoryKind = 'expense' | 'income'

export interface Category {
  id: string
  kind: CategoryKind
  name: string
  color: string
  icon: string
  accountIds: string[]
}

export const CATEGORY_COLORS = [
  '#0F766E',
  '#15803D',
  '#C2410C',
  '#1D4ED8',
  '#7C3AED',
  '#DB2777',
  '#CA8A04',
  '#0E7490',
  '#334155',
  '#64748B',
] as const

export const CATEGORY_ICONS = [
  'grocery',
  'dining',
  'coffee',
  'pizza',
  'wine',
  'sweets',
  'fruit',
  'transport',
  'bus',
  'train',
  'bike',
  'fuel',
  'taxi',
  'home',
  'furniture',
  'utilities',
  'water',
  'repair',
  'pets',
  'kids',
  'health',
  'pharmacy',
  'sport',
  'clinic',
  'shopping',
  'clothes',
  'gadgets',
  'beauty',
  'cart',
  'entertainment',
  'games',
  'music',
  'tickets',
  'party',
  'education',
  'freelance',
  'office',
  'books',
  'travel',
  'hotel',
  'map',
  'salary',
  'investment',
  'cashback',
  'wallet',
  'savings',
  'bank',
  'gifts',
  'family',
  'phone',
  'other',
] as const

export type CategoryIconKey = (typeof CATEGORY_ICONS)[number]

export const CATEGORY_ICON_LABELS: Record<CategoryIconKey, string> = {
  grocery: 'Продукты',
  dining: 'Кафе',
  coffee: 'Кофе',
  pizza: 'Пицца',
  wine: 'Алкоголь',
  sweets: 'Сладости',
  fruit: 'Фрукты',
  transport: 'Авто',
  bus: 'Автобус',
  train: 'Поезд',
  bike: 'Велосипед',
  fuel: 'Бензин',
  taxi: 'Такси',
  home: 'Дом',
  furniture: 'Мебель',
  utilities: 'Коммуналка',
  water: 'Вода',
  repair: 'Ремонт',
  pets: 'Питомцы',
  kids: 'Дети',
  health: 'Здоровье',
  pharmacy: 'Аптека',
  sport: 'Спорт',
  clinic: 'Клиника',
  shopping: 'Покупки',
  clothes: 'Одежда',
  gadgets: 'Техника',
  beauty: 'Красота',
  cart: 'Корзина',
  entertainment: 'Кино',
  games: 'Игры',
  music: 'Музыка',
  tickets: 'Билеты',
  party: 'Праздник',
  education: 'Учёба',
  freelance: 'Подработка',
  office: 'Работа',
  books: 'Книги',
  travel: 'Поездки',
  hotel: 'Отель',
  map: 'Карта',
  salary: 'Зарплата',
  investment: 'Инвестиции',
  cashback: 'Кэшбэк',
  wallet: 'Кошелёк',
  savings: 'Накопления',
  bank: 'Банк',
  gifts: 'Подарки',
  family: 'Семья',
  phone: 'Связь',
  other: 'Другое',
}

export const CATEGORY_ICON_GROUPS: { id: string; label: string; icons: CategoryIconKey[] }[] = [
  {
    id: 'food',
    label: 'Еда',
    icons: ['grocery', 'dining', 'coffee', 'pizza', 'wine', 'sweets', 'fruit'],
  },
  {
    id: 'transport',
    label: 'Транспорт',
    icons: ['transport', 'bus', 'train', 'bike', 'fuel', 'taxi'],
  },
  {
    id: 'home',
    label: 'Дом',
    icons: ['home', 'furniture', 'utilities', 'water', 'repair', 'pets', 'kids'],
  },
  {
    id: 'health',
    label: 'Здоровье',
    icons: ['health', 'pharmacy', 'sport', 'clinic'],
  },
  {
    id: 'shopping',
    label: 'Покупки',
    icons: ['shopping', 'clothes', 'gadgets', 'beauty', 'cart'],
  },
  {
    id: 'leisure',
    label: 'Досуг',
    icons: ['entertainment', 'games', 'music', 'tickets', 'party'],
  },
  {
    id: 'work',
    label: 'Учёба и работа',
    icons: ['education', 'freelance', 'office', 'books'],
  },
  {
    id: 'travel',
    label: 'Поездки',
    icons: ['travel', 'hotel', 'map'],
  },
  {
    id: 'finance',
    label: 'Финансы',
    icons: ['salary', 'investment', 'cashback', 'wallet', 'savings', 'bank'],
  },
  {
    id: 'other',
    label: 'Другое',
    icons: ['gifts', 'family', 'phone', 'other'],
  },
]
