import type { TourContext, TourStepDef } from './types'

export const TOUR_STEPS: TourStepDef[] = [
  {
    id: 'home-create',
    match: (path) => path === '/',
    selector: '[data-tour="home-create"]',
    title: 'Первый счёт',
    description: 'Создайте счёт или подключитесь по коду, если вас пригласили в общий счёт.',
    skipIf: (ctx) => ctx.accountCount > 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'home-balance',
    match: (path) => path === '/',
    selector: '[data-tour="home-balance"]',
    title: 'Баланс',
    description: 'Здесь показан баланс выбранного счёта или всех счетов сразу.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'home-cta',
    match: (path) => path === '/',
    selector: '[data-tour="home-cta"]',
    title: 'Расход и доход',
    description: 'Запишите трату или поступление — баланс обновится сразу.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'nav-expense',
    match: () => true,
    selector: '[data-tour="nav-expense"]',
    title: 'Быстрый расход',
    description: 'Нажмите «+», чтобы записать расход. Удерживайте, чтобы добавить доход.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'top',
    align: 'center',
  },
  {
    id: 'home-chart',
    match: (path) => path === '/',
    selector: '[data-tour="home-chart"]',
    title: 'График расходов и доходов',
    description: 'График показывает расходы или доходы за выбранный период.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'header-account',
    match: (path) => path === '/',
    selector: '[data-tour="header-account"]',
    title: 'Счёт в шапке',
    description: 'Переключайте счёт или смотрите все сразу.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'center',
  },
  {
    id: 'header-menu',
    match: () => true,
    selector: '[data-tour="header-menu"]',
    title: 'Меню',
    description: 'В меню — счета, история, категории, регулярные операции, копилки, перевод между счетами и настройки.',
    skipIf: () => false,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'settings-theme',
    match: (path) => path === '/settings',
    selector: '[data-tour="settings-theme"]',
    title: 'Тема',
    description: 'Светлая, тёмная или как в системе — меняется сразу.',
    skipIf: () => false,
    to: '/settings',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'categories',
    match: (path) => path.startsWith('/categories'),
    selector: '[data-tour="categories"]',
    title: 'Категории',
    description: 'Расход и доход привязываются к категориям. Создайте свои.',
    skipIf: () => false,
    to: '/categories',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'income-rules',
    match: (path) => path === '/income',
    selector: '[data-tour="income-rules"]',
    title: 'Регулярные пополнения',
    description: 'Например, зарплата. Такие пополнения учитываются в прогнозе к дате покупки.',
    skipIf: () => false,
    to: '/income',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'stats-chart',
    match: (path) => path.startsWith('/stats'),
    selector: '[data-tour="stats-chart"]',
    title: 'Статистика',
    description: 'Расходы и доходы за период: категории, дни, динамика и топ операций.',
    skipIf: () => false,
    to: '/stats',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'calendar-cta',
    match: (path) => path.startsWith('/calendar'),
    selector: '[data-tour="calendar-cta"]',
    title: 'Планирование',
    description: 'Запланируйте покупку — приложение проверит, хватит ли денег к дате.',
    skipIf: () => false,
    to: '/calendar',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'account-share',
    match: (path) => path.startsWith('/accounts/') && path !== '/accounts/new',
    selector: '[data-tour="account-share"]',
    title: 'Общий счёт',
    description: 'Поделитесь кодом — другой человек добавит тот же счёт, не копию.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: (ctx) => (ctx.firstAccountId ? `/accounts/${ctx.firstAccountId}` : undefined),
    side: 'bottom',
    align: 'start',
    nextLabel: 'Готово',
  },
]
