import type { TourContext, TourStepDef } from './types'

export const TOUR_STEPS: TourStepDef[] = [
  {
    id: 'home-create',
    match: (path) => path === '/',
    selector: '[data-tour="home-create"]',
    title: 'Первый счёт',
    description: 'Создайте счёт или подключитесь по коду, если вас пригласили в общий счёт.',
    skipIf: (ctx) => ctx.accountCount > 0,
    to: '/',
    side: 'bottom',
    align: 'center',
  },
  {
    id: 'home-balance',
    match: (path) => path === '/',
    selector: '[data-tour="home-balance"]',
    title: 'Баланс',
    description:
      'Выбранный счёт или все сразу. «Доступно до пополнения» уже вычитает планы и регулярные расходы.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'home-upcoming',
    match: (path) => path === '/',
    selector: '[data-tour="home-upcoming"]',
    title: 'Ближайшие 7 дней',
    description: 'Покупки и правила на неделю вперёд. Нажмите строку — откроется планирование.',
    skipIf: (ctx) => ctx.accountCount === 0 || !ctx.hasUpcoming,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'home-cta',
    match: (path) => path === '/',
    selector: '[data-tour="home-cta"]',
    title: 'Расход и доход',
    description:
      'В форме поле «Что записать» разберёт строку в сумму, категорию и дату. Избранное и похожие суммы подставляются при вводе.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'nav-expense',
    match: () => true,
    selector: '[data-tour="nav-expense"]',
    title: 'Нижняя панель',
    description: 'Нажмите «+» — расход. Удерживайте — доход. Справа — перевод между счетами.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'top',
    align: 'center',
  },
  {
    id: 'home-chart',
    match: (path) => path === '/',
    selector: '[data-tour="home-chart"]',
    title: 'График',
    description:
      'Период и вид — расходы или доходы. Нажмите категорию — откроется история с этим фильтром.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'header-account',
    match: (path) => path === '/',
    selector: '[data-tour="header-account"]',
    title: 'Счёт в шапке',
    description:
      'Переключайте счёт или смотрите все сразу. Счета «не в итоге» не входят в общую сумму.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/',
    side: 'bottom',
    align: 'center',
  },
  {
    id: 'header-inbox',
    match: () => true,
    selector: '[data-tour="header-inbox"]',
    title: 'Уведомления',
    description:
      'Изменения на общем счёте и автоначисления. Их можно отменить или поправить сумму.',
    skipIf: () => false,
    to: '/',
    side: 'bottom',
    align: 'end',
  },
  {
    id: 'header-menu',
    match: () => true,
    selector: '[data-tour="header-menu"]',
    title: 'Меню',
    description: 'История, избранное, регулярные, копилки, перевод и настройки — здесь.',
    skipIf: () => false,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'history',
    match: (path) => path.startsWith('/history'),
    selector: '[data-tour="history"]',
    title: 'История',
    description:
      'Период, типы и поиск. Из операции можно повторить, добавить в избранное или сделать регулярной.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/history',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'income-rules',
    match: (path) => path === '/income',
    selector: '[data-tour="income-rules"]',
    title: 'Регулярные',
    description:
      'Пополнения и расходы по расписанию входят в прогноз к дате покупки. Пропуски догоняются при входе.',
    skipIf: () => false,
    to: '/income',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'savings',
    match: (path) => path.startsWith('/savings'),
    selector: '[data-tour="savings"]',
    title: 'Копилки',
    description:
      'Сумма и дата — подскажем, сколько вносить в месяц. Если не укладываетесь — «Как накопить».',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: '/savings',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'calendar-cta',
    match: (path) => path.startsWith('/calendar'),
    selector: '[data-tour="calendar-cta"]',
    title: 'Планирование',
    description:
      'Список или месяц. Покупка проверяет, хватит ли денег — если нет, предложит перевод. Свайп влево — «Куплено» без подтверждения.',
    skipIf: () => false,
    to: '/calendar',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'stats-chart',
    match: (path) => path.startsWith('/stats'),
    selector: '[data-tour="stats-chart"]',
    title: 'Статистика',
    description:
      'Категории, дни, прогноз на 30 или 90 дней, по счетам и участникам. «Сводка и советы» сравнит период с прошлым.',
    skipIf: () => false,
    to: '/stats',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'categories',
    match: (path) => path.startsWith('/categories'),
    selector: '[data-tour="categories"]',
    title: 'Категории',
    description: 'Отдельно для расходов и доходов. Категорию можно привязать не ко всем счетам.',
    skipIf: () => false,
    to: '/categories',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'account-share',
    match: (path) => path.startsWith('/accounts/') && path !== '/accounts/new',
    selector: '[data-tour="account-share"]',
    title: 'Общий счёт',
    description: 'Код даёт тот же счёт, не копию. Участники видят операции; владелец может передать счёт и уйти.',
    skipIf: (ctx) => ctx.accountCount === 0,
    to: (ctx) => (ctx.firstAccountId ? `/accounts/${ctx.firstAccountId}` : undefined),
    side: 'bottom',
    align: 'start',
    nextLabel: 'Готово',
  },
]
