import type { TourContext, TourStepDef } from './types'

function onboarding(skip: (ctx: TourContext) => boolean) {
  return (ctx: TourContext) => ctx.mode !== 'replay' && skip(ctx)
}

export const TOUR_STEPS: TourStepDef[] = [
  {
    id: 'home-accounts',
    match: (path) => path === '/',
    selector: '[data-tour="home-accounts"]',
    title: 'Первый счёт',
    description: 'Нажмите «Создать счёт». Если вас пригласили — рядом кнопка «Ввести код».',
    advanceOn: 'click',
    skipIf: (ctx) => ctx.accountCount > 0,
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'account-form',
    match: () => true,
    selector: '[data-tour="account-form"]',
    title: 'Новый счёт',
    description: 'Укажите название и сколько денег на счёте сейчас, затем нажмите «Сохранить».',
    advanceOn: 'submit',
    skipIf: (ctx) => ctx.accountCount > 0,
    side: 'top',
    align: 'start',
    dock: 'top',
  },
  {
    id: 'nav-settings',
    match: () => true,
    selector: '[data-tour="nav-settings"]',
    title: 'Меню',
    description: 'Нажмите меню — там счета, категории, авто-пополнения и настройки.',
    advanceOn: 'click',
    skipIf: onboarding((ctx) => ctx.accountCount === 0),
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'settings-theme',
    match: (path) => path.startsWith('/settings'),
    selector: '[data-tour="settings-theme"]',
    title: 'Тема',
    description: 'Светлая, тёмная или как в системе — меняется сразу.',
    advanceOn: 'next',
    skipIf: () => false,
    to: '/settings',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'settings-categories',
    match: () => true,
    selector: '[data-tour="settings-categories"]',
    title: 'Категории',
    description: 'Откройте список — расход и доход привязываются к категориям.',
    advanceOn: 'click',
    skipIf: onboarding((ctx) => ctx.accountCount === 0 || (ctx.expenseCategoryCount > 0 && ctx.incomeCategoryCount > 0)),
    openSidebar: true,
    side: 'bottom',
    align: 'start',
    dock: 'bottom',
  },
  {
    id: 'category-expense',
    match: (path) => path.startsWith('/categories'),
    selector: '[data-tour="category-form"]',
    title: 'Категория расхода',
    description: 'Задайте название категории расхода и нажмите «Добавить».',
    advanceOn: 'submit',
    skipIf: onboarding((ctx) => ctx.accountCount === 0 || ctx.expenseCategoryCount > 0),
    to: '/categories',
    side: 'top',
    align: 'start',
    dock: 'top',
  },
  {
    id: 'category-income',
    match: (path) => path.startsWith('/categories'),
    selector: '[data-tour="category-form"]',
    title: 'Категория дохода',
    description: 'Тип уже «Доход» — укажите название и нажмите «Добавить».',
    advanceOn: 'submit',
    skipIf: onboarding((ctx) => ctx.accountCount === 0 || ctx.incomeCategoryCount > 0),
    to: '/categories',
    side: 'top',
    align: 'start',
    dock: 'top',
  },
  {
    id: 'cta-expense',
    match: (path) => path === '/',
    selector: '[data-tour="cta-expense"]',
    title: 'Расход',
    description: 'Нажмите «Расход», чтобы записать трату.',
    advanceOn: 'click',
    skipIf: onboarding((ctx) => ctx.accountCount === 0 || ctx.expenseCategoryCount === 0),
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'expense-form',
    match: () => true,
    selector: '[data-tour="expense-form"]',
    title: 'Расход',
    description: 'Счёт и категория уже выбраны. Укажите сумму и нажмите «Сохранить».',
    advanceOn: 'submit',
    skipIf: onboarding(
      (ctx) => ctx.accountCount === 0 || ctx.expenseCategoryCount === 0 || ctx.expenseCount > 0,
    ),
    to: '/',
    side: 'top',
    align: 'start',
    dock: 'top',
  },
  {
    id: 'cta-income',
    match: (path) => path === '/',
    selector: '[data-tour="cta-income"]',
    title: 'Доход',
    description: 'Нажмите «Доход», чтобы записать поступление.',
    advanceOn: 'click',
    skipIf: onboarding((ctx) => ctx.accountCount === 0 || ctx.incomeCategoryCount === 0),
    to: '/',
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'income-form',
    match: () => true,
    selector: '[data-tour="income-form"]',
    title: 'Доход',
    description: 'Укажите сумму и нажмите «Сохранить».',
    advanceOn: 'submit',
    skipIf: onboarding(
      (ctx) => ctx.accountCount === 0 || ctx.incomeCategoryCount === 0 || ctx.incomeCount > 0,
    ),
    to: '/',
    side: 'top',
    align: 'start',
    dock: 'top',
  },
  {
    id: 'home-account',
    match: (path) => path === '/',
    selector: '[data-tour="home-account"]',
    title: 'Счёт',
    description: 'Откройте карточку — внутри можно поделиться счётом.',
    advanceOn: 'click',
    skipIf: onboarding((ctx) => ctx.accountCount === 0),
    to: '/',
    openSidebar: true,
    side: 'bottom',
    align: 'start',
    dock: 'bottom',
  },
  {
    id: 'account-share',
    match: (path) => path.startsWith('/accounts/') && path !== '/accounts/new',
    selector: '[data-tour="account-share"]',
    title: 'Общий счёт',
    description: 'Вы можете поделиться доступом к счёту и вести его совместно с другим пользователем.',
    advanceOn: 'next',
    skipIf: onboarding((ctx) => ctx.accountCount === 0),
    to: (ctx) => (ctx.firstAccountId ? `/accounts/${ctx.firstAccountId}` : undefined),
    side: 'bottom',
    align: 'start',
  },
  {
    id: 'settings-income',
    match: () => true,
    selector: '[data-tour="settings-income"]',
    title: 'Авто-пополнения',
    description: 'Откройте раздел с регулярными поступлениями.',
    advanceOn: 'click',
    skipIf: onboarding((ctx) => ctx.accountCount === 0),
    openSidebar: true,
    side: 'bottom',
    align: 'start',
    dock: 'bottom',
  },
  {
    id: 'income-rules',
    match: (path) => path === '/income',
    selector: '[data-tour="income-rules"]',
    title: 'Правила пополнения',
    description: 'Добавьте правило — зарплата или перевод раз в месяц попадут в прогноз к дате покупки.',
    advanceOn: 'next',
    skipIf: onboarding((ctx) => ctx.accountCount === 0),
    to: '/income',
    side: 'bottom',
    align: 'start',
    dock: 'bottom',
  },
  {
    id: 'nav-calendar',
    match: () => true,
    selector: '[data-tour="nav-calendar"]',
    title: 'Планирование',
    description: 'Нажмите «Планирование» — здесь планы покупок по счёту.',
    advanceOn: 'click',
    skipIf: (ctx) => ctx.path.startsWith('/calendar'),
    side: 'top',
  },
  {
    id: 'calendar-cta',
    match: (path) => path.startsWith('/calendar'),
    selector: '[data-tour="calendar-cta"]',
    title: 'Планы',
    description: 'Нажмите «Новая покупка» — приложение проверит, хватит ли денег к дате.',
    advanceOn: 'click',
    skipIf: () => false,
    to: '/calendar',
    side: 'bottom',
  },
  {
    id: 'purchase-form',
    match: (path) => path.startsWith('/calendar'),
    selector: '[data-tour="purchase-form"]',
    title: 'Хватит ли денег',
    description:
      'Укажите сумму и дату. Зелёным — хватит к этой дате, если нет — отказ и перевод с другого счёта.',
    advanceOn: 'next',
    skipIf: () => false,
    to: '/calendar',
    side: 'top',
    align: 'start',
    nextLabel: 'Готово',
    dock: 'top',
  },
]
